"""
Django settings for drfdemo project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-41t)x08ngio*dvh4gi#=2o(^k2lh&_s4c@uu%pu)77^clp+gof'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
# This section defines which apps are installed in your Django project

INSTALLED_APPS = [
    # Django's built-in apps (these come with Django)
    'django.contrib.admin',        # Admin interface for managing your data
    'django.contrib.auth',         # User authentication system (login, logout, etc.)
    'django.contrib.contenttypes', # Framework for content types
    'django.contrib.sessions',     # Session framework for storing user data across requests
    'django.contrib.messages',     # Messaging framework for displaying notifications
    'django.contrib.staticfiles',  # Handles static files (CSS, JavaScript, images)
    
    # Third-party apps (installed via pip)
    'rest_framework',              # Django REST Framework - enables API creation
    
    # Your custom apps
    'api',                        # Our custom API app that contains User model and views
]

MIDDLEWARE = [
    # Middleware components process requests and responses
    # They run in order for requests (top to bottom) and in reverse for responses
    
    'django.middleware.security.SecurityMiddleware',     # Adds security-related headers
    'django.contrib.sessions.middleware.SessionMiddleware', # Enables session support
    'django.middleware.common.CommonMiddleware',         # Performs common operations
    'django.middleware.csrf.CsrfViewMiddleware',        # Protects against CSRF attacks
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Adds user to request
    'django.contrib.messages.middleware.MessageMiddleware',    # Enables message framework
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drfdemo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drfdemo.wsgi.application'


# Database configuration
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# This defines how Django connects to your database

DATABASES = {
    'default': {
        # SQLite is a lightweight database stored in a single file
        # Perfect for development and small applications
        'ENGINE': 'django.db.backends.sqlite3',
        
        # Database file location: BASE_DIR/db.sqlite3
        # BASE_DIR is the root directory of your project
        'NAME': BASE_DIR / 'db.sqlite3',
        
        # For production, you might use PostgreSQL or MySQL:
        # 'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': 'your_database_name',
        # 'USER': 'your_database_user',
        # 'PASSWORD': 'your_password',
        # 'HOST': 'localhost',
        # 'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
